/* eslint-disable no-unused-vars */
import React from 'react';

const Home = () => {
    return (
        <div>
            <h2>Home Page</h2>
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis sint ipsum quae! Voluptates tempora architecto aut saepe amet dolorem modi ipsam obcaecati asperiores quasi, placeat odio quisquam, adipisci animi dolore velit, vel alias! Pariatur praesentium quis quibusdam perspiciatis, illo debitis animi fugiat nesciunt facilis maxime laboriosam suscipit impedit quia tempore itaque vel fuga reprehenderit recusandae. Officia reiciendis obcaecati dolore ex inventore recusandae esse modi atque delectus, sapiente necessitatibus animi veniam error incidunt perspiciatis porro beatae? Magnam recusandae nostrum pariatur omnis, nobis numquam praesentium vero voluptate nam voluptatum facilis dignissimos perferendis fugit qui dolorum alias iure ipsum cupiditate saepe ad ab blanditiis. Excepturi adipisci delectus a minus omnis, est enim saepe veniam odit impedit repudiandae officiis, sed vero. Dolorem facere excepturi nulla esse provident, consectetur numquam tempore hic reiciendis ullam corrupti molestias veritatis expedita obcaecati accusamus, voluptas temporibus at, a autem! Nam reiciendis ex, cumque fuga quas ad minus voluptate ipsa perspiciatis soluta eum tempora quidem molestiae corrupti placeat consequuntur, incidunt quis necessitatibus! Nam accusantium impedit tenetur hic beatae deserunt ullam quas, eum dolor omnis placeat laborum veniam ut quia atque, nisi laboriosam quasi dolorum. Consectetur repellendus vel quod eveniet earum dolorum ipsum officia atque, optio nam ratione dolores soluta dicta.
                
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sequi nobis laboriosam quae facilis perspiciatis ullam natus corporis explicabo exercitationem vitae id voluptates quia ad eligendi ex, hic nostrum repellat? Sint temporibus animi vitae laboriosam, sunt aut, quod ex asperiores quam repellendus qui adipisci exercitationem quis obcaecati suscipit, voluptate dolor similique necessitatibus odio assumenda itaque tempora! Molestias suscipit doloremque quis perspiciatis dignissimos quam eius a modi vero dolorum iste consequatur consequuntur eveniet ad dolores, totam excepturi assumenda laudantium hic doloribus harum! Placeat fuga nisi, eum rem tempora nulla et quasi atque autem, quis facere, exercitationem sequi ut aut. Culpa fugit illo unde. Facere quia corrupti consectetur doloribus a, maiores reiciendis facilis ut deserunt reprehenderit eius doloremque ad quisquam, commodi deleniti, voluptas voluptates vel? Rerum voluptas hic, ullam excepturi assumenda odit aliquid maxime veritatis quam maiores laboriosam enim similique magnam rem, eligendi quia consequuntur quasi, iste neque illo numquam labore sit modi. Nam quas maxime provident voluptatum quam, at asperiores, voluptatem architecto perspiciatis qui maiores. Quae id libero pariatur, dicta nihil ex consectetur quia molestiae, repellat sapiente labore qui. Quidem fuga accusamus maxime, asperiores numquam ipsum nostrum non expedita laboriosam quisquam quis. Maiores itaque a adipisci hic! Vero mollitia distinctio consequuntur dolor sint totam ipsum qui ea quis ad error quasi necessitatibus sapiente, numquam, veritatis cum tempore amet, placeat rerum cupiditate repellendus suscipit ipsa nulla. Cum dignissimos, molestias qui ab asperiores modi nisi, laudantium culpa sit esse ea nihil corporis architecto quaerat reprehenderit laborum natus dolores eos at a. Accusantium minima maxime cupiditate tempora fugiat dolorum quod, quae deserunt vero velit possimus eaque nobis dolorem expedita, soluta doloremque. Voluptas ullam quidem adipisci, assumenda repellat ratione laboriosam labore alias ipsum dicta eveniet aperiam recusandae, at quisquam error nobis, accusantium ea ipsa? Sit blanditiis beatae saepe natus quasi voluptas cumque fugit enim provident numquam.
            </p>
        </div>
    );
};

export default Home;